commentapp/urls.py
from django.urls import path, include
from . import views

app_name = 'commentapp'

urlpatterns = [
    path('', views.PostList.as_view(), name='post_list'),
    path('post_create',views.PostCreate.as_view(),name='post_create'),
    path('post_detail/<int:pk>',views.PostDetail.as_view(),name='post_detail'),
    path('post_update/<int:pk>',views.PostUpdate.as_view(),name='post_update'),
    path('post_delete/<int:pk>',views.PostDelete.as_view(),name='post_delete'),
    path('login',views.Login.as_view(),name='login'),
    path('logout',views.Logout.as_view(),name='logout'),
    path('signup',views.SignUp.as_view(),name='signup'),
    path('search',views.Search,name='search'),
]

commentproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('commentapp.urls')),
]

commentapp/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    author=models.ForeignKey(User,on_delete=models.PROTECT,blank=False)
    title=models.CharField('タイトル',max_length=100)
    content=models.TextField('内容',null=True)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

commentapp/forms.py
from django import forms
from .models import Post
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class PostForm(forms.ModelForm):
    class Meta:
        model=Post
        fields=('title','content')

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in self.fields.values():
            field.widget.attrs['class']='form-control'


class LoginForm(AuthenticationForm):
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in self.fields.values():
            field.widget.attrs['class']='form-control'


class SignUpForm(UserCreationForm):
    class Meta:
        model=User
        fields=('username','email','password1','password2')

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in self.fields.values():
            field.widget.attrs['class']='form-control'


class SearchForm(forms.Form):
    freeword=forms.CharField(min_length=1,max_length=30,label='',required=False)
  
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
    

commentapp/views.py
from django.shortcuts import render, resolve_url
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import TemplateView,CreateView,DetailView,UpdateView,DeleteView,ListView 
from .models import Post
from django.urls import reverse_lazy
from .forms import PostForm, LoginForm, SignUpForm, SearchForm
from django.contrib import messages
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Q
from django.core.paginator import Paginator


class OnlyMyPostMixin(UserPassesTestMixin):
    raise_exception=True
    def test_func(self):
        post=Post.objects.get(id=self.kwargs['pk'])
        return post.author==self.request.user


class PostList(ListView):
    model=Post
    paginate_by= 7

    def get_queryset(self):
        if Post.updated_at:
            return Post.objects.all().order_by('-updated_at')
        else:
            return Post.objects.all().order_by('-created_at')


class PostCreate(LoginRequiredMixin,CreateView):
    model=Post
    form_class=PostForm
    success_url=reverse_lazy('commentapp:post_list')

    def form_valid(self,form):
        form.instance.author_id=self.request.user.id
        return super(PostCreate, self).form_valid(form)

    def get_success_url(self):
        messages.success(self.request,'コメントを追加しました。')
        return resolve_url('commentapp:post_list')


class PostDetail(DetailView):
    model=Post

    
class PostUpdate(OnlyMyPostMixin,UpdateView):
    model=Post
    form_class=PostForm

    def get_success_url(self):
        messages.info(self.request,'コメントを編集しました。')
        return resolve_url('commentapp:post_detail',pk=self.kwargs['pk'])


class PostDelete(OnlyMyPostMixin,DeleteView):
    model=Post

    def get_success_url(self):
        messages.info(self.request,'コメントを削除しました。')
        return resolve_url('commentapp:post_list')


class Login(LoginView):
    form_class=LoginForm
    template_name='commentapp/login.html'


class Logout(LogoutView):
    template_name='commentapp/logout.html'


class SignUp(CreateView):
    form_class=SignUpForm
    template_name='commentapp/signup.html'
    success_url=reverse_lazy('commentapp:post_list')

    def form_valid(self,form):
        user=form.save()
        login(self.request, user)
        self.object=user
        messages.info(self.request,'ユーザー登録をしました。')
        return HttpResponseRedirect(self.get_success_url())


def Search(request):
    if request.method=='POST':
        searchform=SearchForm(request.POST)

        if searchform.is_valid():
            freeword=searchform.cleaned_data['freeword']
            search_list=Post.objects.filter(Q(title__icontains=freeword)|Q(content__icontains=freeword))

        params={
            'search_list':search_list,
        }

        return render(request, 'commentapp/search.html',params)

commentapp/templates/commentapp/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>コメント欄</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
  <!-- Google Fonts -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
  <!-- Bootstrap core CSS -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/css/mdb.min.css" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="css/style.css" rel="stylesheet">
</head>

<body>
    <!--Navbar-->
<!--Navbar-->
<nav class="navbar navbar-expand-lg navbar-dark primary-color fixed-top" role="navigation">

  <!-- Navbar brand -->
  <a class="navbar-brand" href="{% url 'commentapp:post_list' %}">Comment</a>

  <!-- Collapse button -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
    aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <!-- Collapsible content -->
  <div class="collapse navbar-collapse" id="basicExampleNav">

    <!-- Links -->
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/admin" target="_blank">管理画面へ</a>
      </li>

      <!-- Dropdown -->
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="account" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">Account</a>
        <div class="dropdown-menu dropdown-primary" aria-labelledby="account">      
          {% if request.user.is_authenticated %}
            <a class="dropdown-item">{{ request.user }}</a>
            <a class="dropdown-item" href="{% url 'commentapp:logout' %}">ログアウト</a>
          {% else %}
            <a class="dropdown-item" href="{% url 'commentapp:login' %}">ログイン</a>
            <a class="dropdown-item" href="{% url 'commentapp:signup' %}">ユーザー登録</a>
          {% endif %}
        </div>
      </li>

    </ul>
    <!-- Links -->

    <form action="{% url 'commentapp:search' %}" class="form-inline my-1" method="POST">
    {% csrf_token %}
    <div class="md-form form-sm my-0">
      <input class="form-control form-control-sm mr-sm-2 mb-0" type="search" placeholder="Search"
        aria-label="Search" name="freeword">
    </div>
    <button class="btn btn-outline-white btn-sm my-0" type="submit">Search</button>
  </form>
  </div>
  <!-- Collapsible content -->

</nav>
<!--/.Navbar-->
<!--/.Navbar-->
    <main class="container" style="padding-top:60px;">
    {% if messages %}
    <br>
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
          {{message}}
        </div>  
      {% endfor %} 
    {% endif %}

    {% block content %}        
    {% endblock %}
    </main>
  <!-- /Start your project here-->

  <!-- Footer -->
<footer class="page-footer font-small blue">

  <!-- Footer Elements -->
  <div class="container">

    <!-- Grid row-->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-12 py-5">
        <div class="mb-5 flex-center">

          <!-- Facebook -->
          <a class="fb-ic" href="https://github.com/Ntsoccer">
            <i class="fab fa-github fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
          </a>
          <!-- Twitter -->
          <a class="tw-ic" href="https://twitter.com/N_T_soccer0512">
            <i class="fab fa-twitter fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
          </a>
        </div>
      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row-->

  </div>
  <!-- Footer Elements -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="/"> Takuya Nishimura</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

  <!-- SCRIPTS -->
  <!-- JQuery -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/js/mdb.min.js"></script>
</body>

</html>

commentapp/templates/commentapp/login.html
{% extends 'commentapp/base.html' %}


{% block content %}
    <div class="row">
        <div class="col-md-6">
        <br>
        <h2>Login</h2>
        <br>

        <form action="" method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}
            {% for field in form %}
                {{field.label}}
                {{field}}
                {{field.errors}}
                <br>
            {% endfor %}
            <button type="submit" class="btn aqua-gradient btn-rounded">Login</button>
            <br>
            <br>
        </form>
        </div>
    </div>

{% endblock content %}
    

commentapp/templates/commentapp/logout.html
{% extends 'commentapp/base.html' %}


{% block content %}
    <div class="row">
        <div class="col-md-6">
            <br>
            <h2>Logout</h2>
            <br>
            <p>ログアウトしました。</p>    
        </div>
    </div>

{% endblock content %}
    

commentapp/templates/commentapp/pagenation.html
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; 最初へ</a>
            <a href="?page={{ page_obj.previous_page_number }}">前へ</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">次へ</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">最後へ &raquo;</a>
        {% endif %}
    </span>
</div>

commentapp/templates/commentapp/post_confirm_delete.html
{% extends 'commentapp/base.html' %}


{% block content %}
    <div class="row">
        <div class="col-md-9">
        <br>
        <h2>コメント削除</h2>
        <br>
        <div class="alert alert-danger" role="alert">
            <form method="post">
                {% csrf_token %}
                <p>以下の内容を本当に削除しますか？</p>
                <input type="submit" class="btn btn-outline-danger" value="削除する"></input>
            </form>
        </div>
        <br>
        <p>タイトル</p>
        {{object.title}}
        <hr>
        <p>内容</p>
        {{object.content}}
        </div>
    </div>
    <br>

{% endblock content %}
    

commentapp/templates/commentapp/post_detail.html
{% extends 'commentapp/base.html' %}

{% block content %}
    <div class="container">  
    <div class="row">
    <div class="col-md-11 mx-auto">
    <br>
    <br>
        <table class="table">
            <thead>
                <tr>
                    <th width="100%"><h4>{{object.title}}</h4><small class="h6">&nbsp;&nbsp;&nbsp;by&nbsp;{{object.author}}</small></th>
                </tr>
            </thead>
        </table>            
        <p class="comment-text">{{object.content|safe|linebreaksbr|urlize}}</p>   
        <hr>
        <br>
        <a href="javascript:void(0);" onclick="window.history.back();" class="btn btn-outline-dark">戻る<a>
        {% if object.author == request.user %}
        <a href="{% url 'commentapp:post_update' object.id %}" class="btn btn-primary">編集<a>
        <a href="{% url 'commentapp:post_delete' object.pk %}" class="btn btn-danger">削除<a>
        {% endif %}
        <br>
        <br>
    </div>
    </div> 
{% endblock content %}
    

commentapp/templates/commentapp/post_form.html
{% extends 'commentapp/base.html' %}


{% block content %}
    <div class="row">
        <div class="col-md-9">
        <br>
        <h2>コメント登録・編集</h2>
        <br>

        <form action="" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label>タイトル</label>
                {{form.title}}
            </div>
            <br>
            <div class="form-group">
                <label>内容</label>
                {{form.content}}
            </div>
            <br>
            <button type="submit" class="btn aqua-gradient btn-rounded">コメントする</button>
            <br>
            <br>
        </form>
        </div>
    </div>

{% endblock content %}
    

commentapp/templates/commentapp/post_list.html
{% extends 'commentapp/base.html' %}


{% block content %}
<!-- Start your project here-->
<div class="jumbotron jumbotron-fluid">
<div class="container">
    <h3 class="display-4 text-center">コメント欄</h3>
    <br>
    <a href="{% url 'commentapp:post_create' %}"><button type="button" class="btn aqua-gradient btn-rounded mx-auto d-block">コメントする</button></a>
</div>
</div>
<br>


<!--start comment-->
<div class="container">  
    <div class="row">
    {% for item in post_list %}
    <div class="col-md-11 mx-auto">
        <table class="table">
            <thead>
                <tr>
                    <th width="100%"><a href="{% url 'commentapp:post_detail' item.id %}"><p class="h4">{{item.title}}</p><small>&nbsp;&nbsp;&nbsp;by&nbsp;{{item.author}}</small>
                    <small class="h6">
                    {% if item.updated_at %}
                        <p class="float-right" width="100%">{{item.updated_at}}<p>
                    {% else %}
                        <p class="float-right" width="100%">{{item.created_at}}<p>
                    {% endif %}
                    </small>
                    </a></th>
                    
                    
                    
                </tr>
            </thead>
        </table>            
        <p class="comment-text">{{item.content|safe|linebreaksbr|urlize}}</p>   
        <hr>
        
        <br>
        <br>
        
    </div>
    {% endfor %} 
 
</div>
{% include 'commentapp/pagenation.html' %}
<br>
<br>
</div> 
{% endblock %}

commentapp/templates/commentapp/search.html
{% extends 'commentapp/base.html' %}


{% block content %}
    <div class="row">
        <div class="col-md-11">
        <br>
        <h2>検索結果</h2>
        <br>
         {% for item in search_list %}
        <div class="col-md-11 mx-auto">
            <table class="table">
                <thead>
                    <tr>
            <th width="100%"><a href="{% url 'commentapp:post_detail' item.id %}"><h4 class="comment-title">{{item.title}}</h4>
                <small>&nbsp;&nbsp;&nbsp;by&nbsp;{{item.author}}</small>
                <small class="h6">
                {% if item.updated_at %}
                    <p class="float-right" width="100%">{{item.updated_at}}<p>
                {% else %}
                    <p class="float-right" width="100%">{{item.created_at}}<p>
                {% endif %}
                </small>
            </a></th>
            </tr>
            </thead>
            <br>
            </table>     
            <p class="comment-text">{{item.content|safe|linebreaksbr|urlize}}</p>   
            <hr>
            <br>
            <br>
        </div>
    {% endfor %}
        </div>
    </div>

{% endblock content %}

commentapp/templates/commentapp/signup.html
{% extends 'commentapp/base.html' %}


{% block content %}
    <div class="row">
        <div class="col-md-6">
        <br>
        <h2>Signup</h2>
        <br>

        <form action="" method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}
            {% for field in form %}
                {{field.label}}
                {{field}}
                {{field.errors}}
                <br>
            {% endfor %}
            <button type="submit" class="btn aqua-gradient btn-rounded">Signup</button>
            <br>
            <br>
        </form>
        </div>
    </div>

{% endblock content %}
    